"""Report generation utilities."""

from __future__ import annotations

from pathlib import Path
import pandas as pd


def write_markdown_summary(
    output_path: str | Path,
    optional_stopping: pd.DataFrame,
    qv_table: pd.DataFrame,
    convergence: pd.DataFrame,
) -> None:
    """Write a compact research summary."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    stopped_mean = optional_stopping.loc[0, "stopped_mean"]
    mean_tau = optional_stopping.loc[0, "mean_stopping_time"]
    qv_final = qv_table.iloc[-1]

    text = f"""# Stochastic Processes & Martingales - Research Summary

This summary is generated by `run_analysis.py`.

## 1. Optional Stopping Experiment

A symmetric random walk was stopped at a bounded first-exit time. The experiment is designed around a clean optional-stopping intuition: bounded stopping should not turn a fair game into a positive-expectation game.

| Metric | Value |
|---|---:|
| Mean stopped value | {stopped_mean:.4f} |
| Mean stopping time | {mean_tau:.2f} |
| Initial mean | {optional_stopping.loc[0, 'initial_mean']:.4f} |

The stopped mean is close to zero, consistent with the martingale structure of the symmetric random walk.

## 2. Quadratic Variation

For Brownian motion on [0,1], quadratic variation should concentrate around 1 as the partition becomes fine.

| n_steps | mean_qv | std_qv |
|---:|---:|---:|
"""
    for _, row in qv_table.iterrows():
        text += f"| {int(row['n_steps'])} | {row['mean_qv']:.4f} | {row['std_qv']:.4f} |\n"

    text += """
## 3. Random Walk Scaling

The scaled terminal value S_n / sqrt(n) should have variance close to one. The table below checks the terminal moments for several step counts.

| n_steps | mean_scaled_terminal | var_scaled_terminal |
|---:|---:|---:|
"""
    for _, row in convergence.iterrows():
        text += f"| {int(row['n_steps'])} | {row['mean_scaled_terminal']:.4f} | {row['var_scaled_terminal']:.4f} |\n"

    text += """
## Interpretation

The simulations are not investment results. They are numerical demonstrations of mathematical structure: martingale fairness, bounded stopping, pathwise quadratic variation, and diffusive scaling. This is the mathematical foundation layer that supports later quantitative research work.
"""
    output_path.write_text(text, encoding="utf-8")
